export type ContentField = { label: string; default: string; multiline?: boolean }
export type PageSchema = { label: string; fields: Record<string, ContentField> }

export const PAGE_CONTENT_SCHEMA: Record<string, PageSchema> = {
  programs: {
    label: 'Programs',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Mental Health & Horticulture Programs' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Structured programs grounded in evidence — bringing together the restorative power of nature and the practical tools of evidence-based psychology. Available to NDIS participants and the broader community.', multiline: true },
      offer_heading: { label: '"What We Offer" Heading', default: 'Programs designed for real life' },
      offer_paragraph: { label: '"What We Offer" Paragraph', default: 'Every Mudleaf program integrates horticulture and mental health skill building — because growth in the garden and growth in the self are not separate processes.', multiline: true },
      program_1_title: { label: 'Program 1 — Title', default: 'MLAT — Mindfulness-based Living & Attention Training' },
      program_1_sub: { label: 'Program 1 — Subtitle', default: 'Online · 12 Weeks · Group & Individual' },
      program_1_desc: { label: 'Program 1 — Description', default: 'A structured 12-week program combining mindfulness, attention regulation, and therapeutic horticulture. Grounded in MBCT and ACT. Available to NDIS participants and the broader community.', multiline: true },
      program_2_title: { label: 'Program 2 — Title', default: 'Therapeutic Horticulture Group Program' },
      program_2_sub: { label: 'Program 2 — Subtitle', default: 'In-Person · Mannum SA · Group' },
      program_2_desc: { label: 'Program 2 — Description', default: 'A hands-on group program using garden-based activities to build practical skills, connection, and wellbeing. Held at our Mannum site. Suitable for NDIS participants and community members.', multiline: true },
      program_3_title: { label: 'Program 3 — Title', default: 'Corporate Wellbeing Programs' },
      program_3_sub: { label: 'Program 3 — Subtitle', default: 'Flexible Delivery · Workplace' },
      program_3_desc: { label: 'Program 3 — Description', default: 'Evidence-based mental health education and therapeutic horticulture experiences for teams. Clinician-led, tailored to your organisation. Half-day and full-day formats available.', multiline: true },
      program_4_title: { label: 'Program 4 — Title', default: 'Tamil Contemplative Traditions' },
      program_4_sub: { label: 'Program 4 — Subtitle', default: 'Online · Reading & Reflection' },
      program_4_desc: { label: 'Program 4 — Description', default: 'An exploration of Tamil philosophical and contemplative traditions — the Thirukkural, Sangam poetry, and their intersections with modern mindfulness and neuroscience.', multiline: true },
      approach_heading: { label: '"The Approach" Heading', default: 'Why horticulture and mental health together' },
      approach_1_title: { label: 'Approach 1 — Title', default: 'Nature as context' },
      approach_1_desc: { label: 'Approach 1 — Description', default: 'Working with plants creates a natural environment for practising attention, patience, and observation — skills that transfer directly into daily life.', multiline: true },
      approach_2_title: { label: 'Approach 2 — Title', default: 'Evidence-based structure' },
      approach_2_desc: { label: 'Approach 2 — Description', default: 'All programs draw on MBCT, ACT, and therapeutic horticulture research. Skills are taught progressively, with each week building on the last.', multiline: true },
      approach_3_title: { label: 'Approach 3 — Title', default: 'Capacity building' },
      approach_3_desc: { label: 'Approach 3 — Description', default: 'The goal is not short-term relief but lasting skill development — building the internal resources to navigate difficulty with greater ease.', multiline: true },
      ndis_heading: { label: 'NDIS Heading', default: 'NDIS participants welcome' },
      ndis_paragraph: { label: 'NDIS Paragraph', default: 'Mudleaf is an unregistered NDIS provider. All programs fall under the Capacity Building support category. Self-managed and plan-managed participants are welcome.', multiline: true },
      ndis_button: { label: 'NDIS Button Text', default: 'NDIS Information →' },
      ndis_bullet_1: { label: 'NDIS Bullet 1', default: 'Self-managed participants — use your plan funds directly' },
      ndis_bullet_2: { label: 'NDIS Bullet 2', default: 'Plan-managed participants — we invoice your plan manager' },
      ndis_bullet_3: { label: 'NDIS Bullet 3', default: 'Service agreements and all documentation provided' },
      ndis_bullet_4: { label: 'NDIS Bullet 4', default: 'Improved Daily Living support category' },
      cta_heading: { label: 'CTA Heading', default: 'Ready to begin?' },
      cta_paragraph: { label: 'CTA Paragraph', default: 'Contact us to discuss which program is the right fit, or register directly for MLAT Level 1.', multiline: true },
      cta_button_1: { label: 'CTA Button 1', default: 'Register for MLAT Level 1' },
      cta_button_2: { label: 'CTA Button 2', default: 'Get in touch' },
    },
  },
  about: {
    label: 'About',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Mudleaf Horticulture, Mental Health & Wellbeing' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Co-founded by Philip and Monica Allan — combining broad expertise in horticulture, mental health, and mindful connected living — all inspired by the restorative power of nature.', multiline: true },
      intro_tag: { label: 'Section Tag', default: 'Where we come from' },
      intro_heading: { label: 'Intro Heading', default: 'Growth happens when people feel supported, connected, and engaged' },
      intro_para_1: { label: 'Intro Paragraph 1', default: 'Mudleaf was established to deliver capacity-building programs that strengthen practical skills in both horticulture and mental health — tailored to the needs of groups and delivered in person and online.', multiline: true },
      intro_para_2: { label: 'Intro Paragraph 2', default: 'By integrating horticultural practice with psychological principles, Mudleaf fosters both practical competence and personal wellbeing. Evidence-based research demonstrates that engaging with plants in structured, mindful ways supports emotional regulation, reduces stress, and enhances self-efficacy.', multiline: true },
      intro_para_3: { label: 'Intro Paragraph 3', default: 'Through this approach, participants are encouraged not only to build confidence in working with plants but also to deepen self-care, mindfulness, and a sense of connection to sustainable, balanced living.', multiline: true },
      philip_name: { label: 'Philip — Name', default: 'Philip Allan' },
      philip_role: { label: 'Philip — Role', default: 'Founder · Horticulture Program Lead' },
      philip_para_1: { label: 'Philip — Paragraph 1', default: 'Philip is a certified horticulture trainer with extensive experience designing and running community programs across South Australia. His community program background spans a wide range of contexts — including 3Ball SA, MCCSA, Afrikarts Music Program, and Infusion, a capacity building program for young people in event management.', multiline: true },
      philip_para_2: { label: 'Philip — Paragraph 2', default: 'Between 2021 and 2024, Philip worked with community nurseries in Townsville, Wagga Wagga, and Katherine — building hands-on knowledge of native plant propagation and community growing across diverse regional and remote Australian settings.', multiline: true },
      philip_para_3: { label: 'Philip — Paragraph 3', default: "Philip is also TEFL certified, bringing a structured approach to adult learning and skills development that underpins Mudleaf's program delivery.", multiline: true },
      monica_name: { label: 'Monica — Name', default: 'Monica Allan' },
      monica_role: { label: 'Monica — Role', default: 'Founder · Mental Health Program Lead' },
      monica_para_1: { label: 'Monica — Paragraph 1', default: 'Monica brings dual qualifications across social work and nursing — a Master of Social Work, Bachelor of Nursing, and Postgraduate qualification in Mental Health Nursing — and is currently completing a Bachelor of Psychology. Her clinical background spans mental health nursing in regional, remote, and telehealth settings; clinical social work practice in metropolitan and regional South Australia; and social work practice in India across sexuality, HIV, and AIDS sectors.', multiline: true },
      monica_para_2: { label: 'Monica — Paragraph 2', default: 'Monica is the creator of MLAT™ — Mindfulness Lived Awareness Training — an original psychoeducational framework integrating neuroscience, evidence-based therapeutic approaches, and Tamil classical contemplative traditions.', multiline: true },
      monica_para_3: { label: 'Monica — Paragraph 3', default: 'Alongside her clinical and research work, she is a practising artist and budding potter whose creative practice is woven into the Mudleaf philosophy of slow, intentional making.', multiline: true },
    },
  },
  ndis: {
    label: 'NDIS',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Supporting NDIS participants to thrive' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Mudleaf is an unregistered NDIS provider welcoming self-managed and plan-managed participants. Our programs focus on building real capacity — skills and wellbeing that extend beyond the session and into everyday life.', multiline: true },
      section1_title: { label: 'Section 1 — Title', default: 'How Mudleaf works with NDIS' },
      section1_para_1: { label: 'Section 1 — Paragraph 1', default: 'As an unregistered NDIS provider, Mudleaf is available to participants who self-manage their funding or who are plan-managed. We are not available to agency-managed participants at this time.', multiline: true },
      section1_para_2: { label: 'Section 1 — Paragraph 2', default: 'All Mudleaf programs are designed under the Capacity Building support category — specifically Improved Daily Living Skills (CB Daily Activity). Our programs build practical, transferable skills in horticulture, emotional regulation, mindfulness, and self-management.', multiline: true },
      section2_title: { label: 'Section 2 — Title', default: 'How to access Mudleaf with your NDIS plan' },
      section2_para_1: { label: 'Section 2 — Paragraph 1', default: 'If you are self-managed, you can pay for Mudleaf services directly from your plan funds and claim reimbursement through the NDIS myplace portal.', multiline: true },
      section2_para_2: { label: 'Section 2 — Paragraph 2', default: 'If you are plan-managed, your plan manager can pay Mudleaf directly. Contact us first and we will provide a service agreement and invoice template to share with your plan manager.', multiline: true },
      section2_para_3: { label: 'Section 2 — Paragraph 3', default: 'We do not require a support coordinator to access most programs, though we are happy to liaise with your support coordinator if you have one.', multiline: true },
      section3_title: { label: 'Section 3 — Title', default: 'Service agreements and invoicing' },
      section3_para_1: { label: 'Section 3 — Paragraph 1', default: 'We provide a written service agreement prior to commencing any program. Invoices include the NDIS support item number, unit price, and quantity of units — in the format required for NDIS claiming and plan management.', multiline: true },
      section3_para_2: { label: 'Section 3 — Paragraph 2', default: 'Contact us at enquiries@mudleaf.com.au to discuss your needs and we will provide all the documentation required to get started.', multiline: true },
      section4_title: { label: 'Section 4 — Title', default: 'What participants can access' },
      section4_item_1: { label: 'Access Item 1', default: 'MLAT™ — Mindfulness Lived Awareness Training (online, 8–12 week programs)' },
      section4_item_2: { label: 'Access Item 2', default: 'Therapeutic horticulture workshops (in-person group, Mannum SA)' },
      section4_item_3: { label: 'Access Item 3', default: 'Group programs focused on social connection and community participation' },
      section4_item_4: { label: 'Access Item 4', default: 'Digital workbooks and self-guided resources' },
      sidebar_heading: { label: 'Sidebar — Heading', default: 'Ready to get started?' },
      sidebar_paragraph: { label: 'Sidebar — Paragraph', default: 'Contact us to discuss your NDIS plan and which programs are right for you. We respond within two business days.', multiline: true },
      sidebar_button: { label: 'Sidebar — Button', default: 'Get in touch' },
      card1_title: { label: 'Card 1 — Title', default: 'Provider status' },
      card1_detail: { label: 'Card 1 — Detail', default: 'Unregistered NDIS Provider\nABN: [ABN number]\nAvailable to: Self-managed, Plan-managed', multiline: true },
      card2_title: { label: 'Card 2 — Title', default: 'Support category' },
      card2_detail: { label: 'Card 2 — Detail', default: 'Capacity Building — Improved Daily Living (CB Daily Activity)\nSupport item: 09_009_0117_6_3', multiline: true },
      card3_title: { label: 'Card 3 — Title', default: 'Location' },
      card3_detail: { label: 'Card 3 — Detail', default: 'In-person: Mannum SA 5238\nOnline programs: Available nationally', multiline: true },
    },
  },
}
