export type ContentField = { label: string; default: string; multiline?: boolean }
export type PageSchema = { label: string; fields: Record<string, ContentField> }

export const PAGE_CONTENT_SCHEMA: Record<string, PageSchema> = {
  home: {
    label: 'Home',
    fields: {
      hero_tag: { label: 'Hero — Location Tag', default: 'Mannum, South Australia' },
      hero_title: { label: 'Hero — Title', default: 'Where growth begins in nature' },
      hero_subtitle: { label: 'Hero — Subtitle', default: 'Mudleaf combines the restorative power of working with plants with structured, evidence-based mental health skill building — designed to build capacity, resilience, and genuine wellbeing through group and online programs.', multiline: true },
      hero_btn_1: { label: 'Hero — Button 1', default: 'Explore Our Programs' },
      hero_btn_2: { label: 'Hero — Button 2', default: 'NDIS Information' },
      card_1_title: { label: 'Hero Card 1 — Title', default: 'MH & Horticulture Programs' },
      card_1_desc: { label: 'Hero Card 1 — Description', default: 'Group and online programs combining therapeutic horticulture and evidence-based mental health skill building.', multiline: true },
      card_2_title: { label: 'Hero Card 2 — Title', default: 'NDIS Information' },
      card_2_desc: { label: 'Hero Card 2 — Description', default: 'Unregistered provider welcoming self-managed and plan-managed participants. Capacity building focus.', multiline: true },
      card_3_title: { label: 'Hero Card 3 — Title', default: 'Corporate Programs' },
      card_3_desc: { label: 'Hero Card 3 — Description', default: 'Evidence-based mental health education and nature-based wellbeing experiences for workplaces.', multiline: true },
      photo_1_label: { label: 'Photo 1 — Caption', default: 'Mannum, South Australia' },
      photo_2_label: { label: 'Photo 2 — Caption', default: 'Native flora' },
      photo_3_label: { label: 'Photo 3 — Caption', default: 'Grown in country' },
    },
  },
  about: {
    label: 'About',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Mudleaf Horticulture, Mental Health & Wellbeing' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Co-founded by Philip and Monica Allan — combining broad expertise in horticulture, mental health, and mindful connected living — all inspired by the restorative power of nature.', multiline: true },
      intro_tag: { label: 'Section Tag', default: 'Where we come from' },
      intro_heading: { label: 'Intro Heading', default: 'Growth happens when people feel supported, connected, and engaged' },
      intro_para_1: { label: 'Intro Paragraph 1', default: 'Mudleaf was established to deliver capacity-building programs that strengthen practical skills in both horticulture and mental health — tailored to the needs of groups and delivered in person and online.', multiline: true },
      intro_para_2: { label: 'Intro Paragraph 2', default: 'By integrating horticultural practice with psychological principles, Mudleaf fosters both practical competence and personal wellbeing. Evidence-based research demonstrates that engaging with plants in structured, mindful ways supports emotional regulation, reduces stress, and enhances self-efficacy.', multiline: true },
      intro_para_3: { label: 'Intro Paragraph 3', default: 'Through this approach, participants are encouraged not only to build confidence in working with plants but also to deepen self-care, mindfulness, and a sense of connection to sustainable, balanced living.', multiline: true },
      philip_name: { label: 'Philip — Name', default: 'Philip Allan' },
      philip_role: { label: 'Philip — Role', default: 'Founder · Horticulture Program Lead' },
      philip_para_1: { label: 'Philip — Paragraph 1', default: 'Philip is a certified horticulture trainer with extensive experience designing and running community programs across South Australia. His community program background spans a wide range of contexts — including 3Ball SA, MCCSA, Afrikarts Music Program, and Infusion, a capacity building program for young people in event management.', multiline: true },
      philip_para_2: { label: 'Philip — Paragraph 2', default: 'Between 2021 and 2024, Philip worked with community nurseries in Townsville, Wagga Wagga, and Katherine — building hands-on knowledge of native plant propagation and community growing across diverse regional and remote Australian settings.', multiline: true },
      philip_para_3: { label: 'Philip — Paragraph 3', default: "Philip is also TEFL certified, bringing a structured approach to adult learning and skills development that underpins Mudleaf's program delivery.", multiline: true },
      monica_name: { label: 'Monica — Name', default: 'Monica Allan' },
      monica_role: { label: 'Monica — Role', default: 'Founder · Mental Health Program Lead' },
      monica_para_1: { label: 'Monica — Paragraph 1', default: 'Monica brings dual qualifications across social work and nursing — a Master of Social Work, Bachelor of Nursing, and Postgraduate qualification in Mental Health Nursing — and is currently completing a Bachelor of Psychology. Her clinical background spans mental health nursing in regional, remote, and telehealth settings; clinical social work practice in metropolitan and regional South Australia; and social work practice in India across sexuality, HIV, and AIDS sectors.', multiline: true },
      monica_para_2: { label: 'Monica — Paragraph 2', default: 'Monica is the creator of MLAT™ — Mindfulness Lived Awareness Training — an original psychoeducational framework integrating neuroscience, evidence-based therapeutic approaches, and Tamil classical contemplative traditions.', multiline: true },
      monica_para_3: { label: 'Monica — Paragraph 3', default: 'Alongside her clinical and research work, she is a practising artist and budding potter whose creative practice is woven into the Mudleaf philosophy of slow, intentional making.', multiline: true },
    },
  },
  ndis: {
    label: 'NDIS',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Supporting NDIS participants to thrive' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Mudleaf is an unregistered NDIS provider welcoming self-managed and plan-managed participants. Our programs focus on building real capacity — skills and wellbeing that extend beyond the session and into everyday life.', multiline: true },
      section1_title: { label: 'Section 1 — Title', default: 'How Mudleaf works with NDIS' },
      section1_para_1: { label: 'Section 1 — Paragraph 1', default: 'As an unregistered NDIS provider, Mudleaf is available to participants who self-manage their funding or who are plan-managed. We are not available to agency-managed participants at this time.', multiline: true },
      section1_para_2: { label: 'Section 1 — Paragraph 2', default: 'All Mudleaf programs are designed under the Capacity Building support category — specifically Improved Daily Living Skills (CB Daily Activity). Our programs build practical, transferable skills in horticulture, emotional regulation, mindfulness, and self-management.', multiline: true },
      section2_title: { label: 'Section 2 — Title', default: 'How to access Mudleaf with your NDIS plan' },
      section2_para_1: { label: 'Section 2 — Paragraph 1', default: 'If you are self-managed, you can pay for Mudleaf services directly from your plan funds and claim reimbursement through the NDIS myplace portal.', multiline: true },
      section2_para_2: { label: 'Section 2 — Paragraph 2', default: 'If you are plan-managed, your plan manager can pay Mudleaf directly. Contact us first and we will provide a service agreement and invoice template to share with your plan manager.', multiline: true },
      section2_para_3: { label: 'Section 2 — Paragraph 3', default: 'We do not require a support coordinator to access most programs, though we are happy to liaise with your support coordinator if you have one.', multiline: true },
      section3_title: { label: 'Section 3 — Title', default: 'Service agreements and invoicing' },
      section3_para_1: { label: 'Section 3 — Paragraph 1', default: 'We provide a written service agreement prior to commencing any program. Invoices include the NDIS support item number, unit price, and quantity of units — in the format required for NDIS claiming and plan management.', multiline: true },
      section3_para_2: { label: 'Section 3 — Paragraph 2', default: 'Contact us at enquiries@mudleaf.com.au to discuss your needs and we will provide all the documentation required to get started.', multiline: true },
      section4_title: { label: 'Section 4 — Title', default: 'What participants can access' },
      section4_item_1: { label: 'Access Item 1', default: 'MLAT™ — Mindfulness Lived Awareness Training (online, 8–12 week programs)' },
      section4_item_2: { label: 'Access Item 2', default: 'Therapeutic horticulture workshops (in-person group, Mannum SA)' },
      section4_item_3: { label: 'Access Item 3', default: 'Group programs focused on social connection and community participation' },
      section4_item_4: { label: 'Access Item 4', default: 'Digital workbooks and self-guided resources' },
      sidebar_heading: { label: 'Sidebar — Heading', default: 'Ready to get started?' },
      sidebar_paragraph: { label: 'Sidebar — Paragraph', default: 'Contact us to discuss your NDIS plan and which programs are right for you. We respond within two business days.', multiline: true },
      sidebar_button: { label: 'Sidebar — Button', default: 'Get in touch' },
      card1_title: { label: 'Card 1 — Title', default: 'Provider status' },
      card1_detail: { label: 'Card 1 — Detail', default: 'Unregistered NDIS Provider\nABN: [ABN number]\nAvailable to: Self-managed, Plan-managed', multiline: true },
      card2_title: { label: 'Card 2 — Title', default: 'Support category' },
      card2_detail: { label: 'Card 2 — Detail', default: 'Capacity Building — Improved Daily Living (CB Daily Activity)\nSupport item: 09_009_0117_6_3', multiline: true },
      card3_title: { label: 'Card 3 — Title', default: 'Location' },
      card3_detail: { label: 'Card 3 — Detail', default: 'In-person: Mannum SA 5238\nOnline programs: Available nationally', multiline: true },
    },
  },
  programs: {
    label: 'Programs',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Mental Health & Horticulture Programs' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Structured programs grounded in evidence — bringing together the restorative power of nature and the practical tools of evidence-based psychology. Available to NDIS participants and the broader community.', multiline: true },
      offer_heading: { label: '"What We Offer" Heading', default: 'Programs designed for real life' },
      offer_paragraph: { label: '"What We Offer" Paragraph', default: 'Every Mudleaf program integrates horticulture and mental health skill building — because growth in the garden and growth in the self are not separate processes.', multiline: true },
      program_1_title: { label: 'Program 1 — Title', default: 'MLAT — Mindfulness-based Living & Attention Training' },
      program_1_sub: { label: 'Program 1 — Subtitle', default: 'Online · 12 Weeks · Group & Individual' },
      program_1_desc: { label: 'Program 1 — Description', default: 'A structured 12-week program combining mindfulness, attention regulation, and therapeutic horticulture. Grounded in MBCT and ACT. Available to NDIS participants and the broader community.', multiline: true },
      program_2_title: { label: 'Program 2 — Title', default: 'Therapeutic Horticulture Group Program' },
      program_2_sub: { label: 'Program 2 — Subtitle', default: 'In-Person · Mannum SA · Group' },
      program_2_desc: { label: 'Program 2 — Description', default: 'A hands-on group program using garden-based activities to build practical skills, connection, and wellbeing. Held at our Mannum site. Suitable for NDIS participants and community members.', multiline: true },
      program_3_title: { label: 'Program 3 — Title', default: 'Corporate Wellbeing Programs' },
      program_3_sub: { label: 'Program 3 — Subtitle', default: 'Flexible Delivery · Workplace' },
      program_3_desc: { label: 'Program 3 — Description', default: 'Evidence-based mental health education and therapeutic horticulture experiences for teams. Clinician-led, tailored to your organisation. Half-day and full-day formats available.', multiline: true },
      program_4_title: { label: 'Program 4 — Title', default: 'Tamil Contemplative Traditions' },
      program_4_sub: { label: 'Program 4 — Subtitle', default: 'Online · Reading & Reflection' },
      program_4_desc: { label: 'Program 4 — Description', default: 'An exploration of Tamil philosophical and contemplative traditions — the Thirukkural, Sangam poetry, and their intersections with modern mindfulness and neuroscience.', multiline: true },
      approach_heading: { label: '"The Approach" Heading', default: 'Why horticulture and mental health together' },
      approach_1_title: { label: 'Approach 1 — Title', default: 'Nature as context' },
      approach_1_desc: { label: 'Approach 1 — Description', default: 'Working with plants creates a natural environment for practising attention, patience, and observation — skills that transfer directly into daily life.', multiline: true },
      approach_2_title: { label: 'Approach 2 — Title', default: 'Evidence-based structure' },
      approach_2_desc: { label: 'Approach 2 — Description', default: 'All programs draw on MBCT, ACT, and therapeutic horticulture research. Skills are taught progressively, with each week building on the last.', multiline: true },
      approach_3_title: { label: 'Approach 3 — Title', default: 'Capacity building' },
      approach_3_desc: { label: 'Approach 3 — Description', default: 'The goal is not short-term relief but lasting skill development — building the internal resources to navigate difficulty with greater ease.', multiline: true },
      ndis_heading: { label: 'NDIS Heading', default: 'NDIS participants welcome' },
      ndis_paragraph: { label: 'NDIS Paragraph', default: 'Mudleaf is an unregistered NDIS provider. All programs fall under the Capacity Building support category. Self-managed and plan-managed participants are welcome.', multiline: true },
      ndis_button: { label: 'NDIS Button Text', default: 'NDIS Information →' },
      ndis_bullet_1: { label: 'NDIS Bullet 1', default: 'Self-managed participants — use your plan funds directly' },
      ndis_bullet_2: { label: 'NDIS Bullet 2', default: 'Plan-managed participants — we invoice your plan manager' },
      ndis_bullet_3: { label: 'NDIS Bullet 3', default: 'Service agreements and all documentation provided' },
      ndis_bullet_4: { label: 'NDIS Bullet 4', default: 'Improved Daily Living support category' },
      cta_heading: { label: 'CTA Heading', default: 'Ready to begin?' },
      cta_paragraph: { label: 'CTA Paragraph', default: 'Contact us to discuss which program is the right fit, or register directly for MLAT Level 1.', multiline: true },
      cta_button_1: { label: 'CTA Button 1', default: 'Register for MLAT Level 1' },
      cta_button_2: { label: 'CTA Button 2', default: 'Get in touch' },
    },
  },
  corporate: {
    label: 'Corporate',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Workplace wellbeing grounded in evidence' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Clinician-led mental health education and therapeutic horticulture experiences for teams. Designed for organisations that take staff wellbeing seriously.', multiline: true },
      intro_heading: { label: 'Intro Heading', default: 'Not a wellness day. A genuine learning experience.' },
      intro_para_1: { label: 'Intro Paragraph 1', default: 'Mudleaf corporate programs are designed and delivered by clinicians — not facilitators with a mindfulness app. The content is grounded in neuroscience, evidence-based psychology, and the practical reality of working life.', multiline: true },
      intro_para_2: { label: 'Intro Paragraph 2', default: 'We combine structured mental health education with hands-on therapeutic horticulture activities — creating an experience that is both intellectually substantial and genuinely restorative.', multiline: true },
      intro_para_3: { label: 'Intro Paragraph 3', default: "Programs are tailored to your organisation's context, team size, and goals. Available as half-day, full-day, or multi-session formats.", multiline: true },
      feat_1_title: { label: 'Feature 1 — Title', default: 'Mental health literacy' },
      feat_1_desc: { label: 'Feature 1 — Description', default: 'Evidence-based education on stress, attention, emotion regulation, and psychological safety — delivered in plain language, without jargon.', multiline: true },
      feat_2_title: { label: 'Feature 2 — Title', default: 'Therapeutic horticulture' },
      feat_2_desc: { label: 'Feature 2 — Description', default: 'Hands-on garden activities that build practical mindfulness skills in a natural setting. No prior gardening experience required.', multiline: true },
      feat_3_title: { label: 'Feature 3 — Title', default: 'Clinician-led' },
      feat_3_desc: { label: 'Feature 3 — Description', default: 'Designed and delivered by Monica Allan MSW, BN, PG Mental Health Nursing — bringing clinical expertise into the workplace context.', multiline: true },
      feat_4_title: { label: 'Feature 4 — Title', default: 'Tailored to your team' },
      feat_4_desc: { label: 'Feature 4 — Description', default: 'Content is adapted to your industry, team size, and specific goals. We work with you before the program to understand your context.', multiline: true },
      format_1_title: { label: 'Format 1 — Title', default: 'Half-Day Intensive' },
      format_1_duration: { label: 'Format 1 — Duration', default: '3–4 hours' },
      format_1_desc: { label: 'Format 1 — Description', default: 'A focused introduction to mindfulness, stress physiology, and attention regulation — combined with a guided horticulture activity. Suitable for team half-days and professional development.', multiline: true },
      format_2_title: { label: 'Format 2 — Title', default: 'Full-Day Program' },
      format_2_duration: { label: 'Format 2 — Duration', default: '6–7 hours' },
      format_2_desc: { label: 'Format 2 — Description', default: 'A comprehensive day covering psychological skills, therapeutic horticulture practice, and group reflection. Includes a facilitated debrief and individual resource pack.', multiline: true },
      format_3_title: { label: 'Format 3 — Title', default: 'Multi-Session Series' },
      format_3_duration: { label: 'Format 3 — Duration', default: '4–6 weeks' },
      format_3_desc: { label: 'Format 3 — Description', default: 'A structured program delivered across multiple sessions — building skills progressively and allowing time for practice between sessions. Most effective for sustained change.', multiline: true },
      audience_heading: { label: 'Audience Heading', default: 'Organisations that invest in their people' },
      audience_para_1: { label: 'Audience Paragraph 1', default: 'Mudleaf corporate programs are suited to any organisation where staff wellbeing, psychological safety, and sustainable performance matter — from small businesses to large enterprises.', multiline: true },
      audience_para_2: { label: 'Audience Paragraph 2', default: "We work particularly well with healthcare, education, social services, and community sector organisations — where staff regularly carry the weight of others' difficulties.", multiline: true },
      cta_heading: { label: 'CTA Heading', default: 'Talk to us about your organisation' },
      cta_paragraph: { label: 'CTA Paragraph', default: "Every program is tailored. Tell us about your team, your context, and what you're hoping to achieve — and we'll put together a proposal.", multiline: true },
    },
  },
  contact: {
    label: 'Contact',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Get in touch' },
      hero_subtitle: { label: 'Hero Subtitle', default: "Whether you're a participant, a support coordinator, a referrer, or a researcher — we'd like to hear from you.", multiline: true },
      response_heading: { label: 'Response Heading', default: 'We respond within two business days' },
      response_para: { label: 'Response Paragraph', default: 'For NDIS enquiries, please include your plan management type (self-managed or plan-managed) and the program you\'re interested in. We\'ll send you a service agreement and all the documentation you need to get started.', multiline: true },
      email_label: { label: 'Email Label', default: 'Email' },
      email_value: { label: 'Email Address', default: 'enquiries@mudleaf.com.au' },
      location_label: { label: 'Location Label', default: 'Location' },
      location_value: { label: 'Location Detail', default: 'Mannum SA 5238, Australia\nOnline programs available nationally', multiline: true },
      ndis_label: { label: 'NDIS Note Label', default: 'NDIS Enquiries' },
      ndis_value: { label: 'NDIS Note Detail', default: 'Self-managed and plan-managed participants welcome. Service agreements provided on request.', multiline: true },
    },
  },
  feedback: {
    label: 'Feedback',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Feedback & Concerns' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Your experience matters to us. Whether you want to share what is working, raise a concern, suggest something, or tell us something we need to hear — this is the place to do it.', multiline: true },
      intro_heading: { label: 'Intro Heading', default: 'We want to hear from you' },
      intro_para_1: { label: 'Intro Paragraph 1', default: 'Mudleaf is a community-facing practice. That means the people who participate in our programs, work alongside us, or encounter our services have a genuine voice in how we operate.', multiline: true },
      intro_para_2: { label: 'Intro Paragraph 2', default: 'We welcome all feedback — positive, constructive, and critical. If something in a program did not work for you, if you experienced something that felt wrong, or if you have an idea that could make Mudleaf better, we want to know.', multiline: true },
      intro_para_3: { label: 'Intro Paragraph 3', default: 'All feedback is received by Monica Allan directly. You can choose to share your name and contact details, or submit anonymously.', multiline: true },
      type_1_title: { label: 'Type 1 — Title', default: 'Program feedback' },
      type_1_desc: { label: 'Type 1 — Description', default: "What worked, what didn't, what you wish had been different — about any Mudleaf program or session.", multiline: true },
      type_2_title: { label: 'Type 2 — Title', default: 'Concerns' },
      type_2_desc: { label: 'Type 2 — Description', default: 'If something felt unsafe, inappropriate, or contrary to your dignity and rights — please tell us. We take these matters seriously and will respond promptly.', multiline: true },
      type_3_title: { label: 'Type 3 — Title', default: 'Suggestions' },
      type_3_desc: { label: 'Type 3 — Description', default: 'Ideas for new programs, content, resources, or ways of working that could better serve participants and the community.', multiline: true },
      type_4_title: { label: 'Type 4 — Title', default: 'Compliments' },
      type_4_desc: { label: 'Type 4 — Description', default: 'If something made a genuine difference — we want to know that too. It helps us understand what matters most.', multiline: true },
    },
  },
  shop: {
    label: 'Shop',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Mudleaf Resources & Digital Products' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Practical tools for participants, practitioners, and curious minds. Designed with the same evidence-based care as our programs.', multiline: true },
      products_heading: { label: 'Products Heading', default: 'Workbooks & journals' },
      products_paragraph: { label: 'Products Paragraph', default: 'All digital products are available through our Etsy shop — instant download, editable PDF format, designed for real use.', multiline: true },
      etsy_heading: { label: 'Etsy Section Heading', default: 'Visit our Etsy shop' },
      etsy_paragraph: { label: 'Etsy Section Paragraph', default: 'All Mudleaf digital products are available through MudLeaf LoveLifeMadly on Etsy. Secure checkout, instant download.', multiline: true },
      ndis_heading: { label: 'NDIS Section Heading', default: 'NDIS participants' },
      ndis_paragraph: { label: 'NDIS Section Paragraph', default: 'Some digital products may be claimable under your NDIS plan as capacity building resources. Contact us to discuss your plan and we will provide the appropriate documentation.', multiline: true },
    },
  },
  footer: {
    label: 'Footer',
    fields: {
      trademark_line: { label: 'Trademark Line', default: 'Mudleaf™ and MLAT™ are trade marks of Mudleaf.\nTrade mark applications pending — IP Australia.', multiline: true },
      copyright_line: { label: 'Copyright Line', default: '© 2026 Mudleaf. ABN [number]. Founded by Monica & Philip Allan.' },
      youtube_label: { label: 'YouTube Link Label', default: 'LoveLifeMadly' },
      etsy_label: { label: 'Etsy Link Label', default: 'Etsy Shop' },
    },
  },
}

