export type ContentField = { label: string; default: string; multiline?: boolean }
export type PageSchema = { label: string; fields: Record<string, ContentField> }

export const PAGE_CONTENT_SCHEMA: Record<string, PageSchema> = {
  programs: {
    label: 'Programs',
    fields: {
      hero_title: { label: 'Hero Title', default: 'Mental Health & Horticulture Programs' },
      hero_subtitle: { label: 'Hero Subtitle', default: 'Structured programs grounded in evidence — bringing together the restorative power of nature and the practical tools of evidence-based psychology. Available to NDIS participants and the broader community.', multiline: true },
      offer_heading: { label: '"What We Offer" Heading', default: 'Programs designed for real life' },
      offer_paragraph: { label: '"What We Offer" Paragraph', default: 'Every Mudleaf program integrates horticulture and mental health skill building — because growth in the garden and growth in the self are not separate processes.', multiline: true },
      program_1_title: { label: 'Program 1 — Title', default: 'MLAT — Mindfulness-based Living & Attention Training' },
      program_1_sub: { label: 'Program 1 — Subtitle', default: 'Online · 12 Weeks · Group & Individual' },
      program_1_desc: { label: 'Program 1 — Description', default: 'A structured 12-week program combining mindfulness, attention regulation, and therapeutic horticulture. Grounded in MBCT and ACT. Available to NDIS participants and the broader community.', multiline: true },
      program_2_title: { label: 'Program 2 — Title', default: 'Therapeutic Horticulture Group Program' },
      program_2_sub: { label: 'Program 2 — Subtitle', default: 'In-Person · Mannum SA · Group' },
      program_2_desc: { label: 'Program 2 — Description', default: 'A hands-on group program using garden-based activities to build practical skills, connection, and wellbeing. Held at our Mannum site. Suitable for NDIS participants and community members.', multiline: true },
      program_3_title: { label: 'Program 3 — Title', default: 'Corporate Wellbeing Programs' },
      program_3_sub: { label: 'Program 3 — Subtitle', default: 'Flexible Delivery · Workplace' },
      program_3_desc: { label: 'Program 3 — Description', default: 'Evidence-based mental health education and therapeutic horticulture experiences for teams. Clinician-led, tailored to your organisation. Half-day and full-day formats available.', multiline: true },
      program_4_title: { label: 'Program 4 — Title', default: 'Tamil Contemplative Traditions' },
      program_4_sub: { label: 'Program 4 — Subtitle', default: 'Online · Reading & Reflection' },
      program_4_desc: { label: 'Program 4 — Description', default: 'An exploration of Tamil philosophical and contemplative traditions — the Thirukkural, Sangam poetry, and their intersections with modern mindfulness and neuroscience.', multiline: true },
      approach_heading: { label: '"The Approach" Heading', default: 'Why horticulture and mental health together' },
      approach_1_title: { label: 'Approach 1 — Title', default: 'Nature as context' },
      approach_1_desc: { label: 'Approach 1 — Description', default: 'Working with plants creates a natural environment for practising attention, patience, and observation — skills that transfer directly into daily life.', multiline: true },
      approach_2_title: { label: 'Approach 2 — Title', default: 'Evidence-based structure' },
      approach_2_desc: { label: 'Approach 2 — Description', default: 'All programs draw on MBCT, ACT, and therapeutic horticulture research. Skills are taught progressively, with each week building on the last.', multiline: true },
      approach_3_title: { label: 'Approach 3 — Title', default: 'Capacity building' },
      approach_3_desc: { label: 'Approach 3 — Description', default: 'The goal is not short-term relief but lasting skill development — building the internal resources to navigate difficulty with greater ease.', multiline: true },
      ndis_heading: { label: 'NDIS Heading', default: 'NDIS participants welcome' },
      ndis_paragraph: { label: 'NDIS Paragraph', default: 'Mudleaf is an unregistered NDIS provider. All programs fall under the Capacity Building support category. Self-managed and plan-managed participants are welcome.', multiline: true },
      ndis_button: { label: 'NDIS Button Text', default: 'NDIS Information →' },
      ndis_bullet_1: { label: 'NDIS Bullet 1', default: 'Self-managed participants — use your plan funds directly' },
      ndis_bullet_2: { label: 'NDIS Bullet 2', default: 'Plan-managed participants — we invoice your plan manager' },
      ndis_bullet_3: { label: 'NDIS Bullet 3', default: 'Service agreements and all documentation provided' },
      ndis_bullet_4: { label: 'NDIS Bullet 4', default: 'Improved Daily Living support category' },
      cta_heading: { label: 'CTA Heading', default: 'Ready to begin?' },
      cta_paragraph: { label: 'CTA Paragraph', default: 'Contact us to discuss which program is the right fit, or register directly for MLAT Level 1.', multiline: true },
      cta_button_1: { label: 'CTA Button 1', default: 'Register for MLAT Level 1' },
      cta_button_2: { label: 'CTA Button 2', default: 'Get in touch' },
    },
  },
}
